# This file is a template, and might need editing before it works on your project.
# variables:
#   GIT_SUBMODULE_STRATEGY: recursive

image: node:14

stages:
  - test
  - build-and-deploy

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

before_script:
  # Create ssh-key and pull submodule
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - echo -e "$SSH_DEPLOY_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - git submodule update --init --recursive

test:
  stage: test
  variables:
    AWS_S3_PREFIX: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
  script:
    - export AWS_S3_BUCKET=$AWS_S3_BUCKET_BETA
    - echo "$AWS_S3_PREFIX"
    - echo "$AWS_S3_BUCKET"
    - echo "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
    - npm install
    - npm run build --prefix-paths
  only:
    - merge_requests
  except:
    - develop
    - master
  tags:
    - hcm-share-docker-runner-1


build-and-deploy-beta:
  stage: build-and-deploy
  script:
    - export AWS_S3_BUCKET=$AWS_S3_BUCKET_BETA
    - npm install
    - npm run build
    - npm run deploy
  only:
    - develop
  tags:
    - hcm-share-docker-runner-1

build-and-deploy:
  stage: build-and-deploy
  script:
    - npm install
    - npm run build
    - npm run deploy
  only:
    - master
  tags:
    - hcm-share-docker-runner-1

