image: node:14

stages:
  - lint
  - build

# Cache the folder node_modules
cache:
  paths:
    - node_modules/

before_script:
  # Copy from the old file .gitlab-ci.yml
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - echo -e "$SSH_DEPLOY_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - git submodule update --init --recursive

lint_jobs:
  stage: lint
  script: 
    - npm i
    - npm run lint
  only:
    - merge_requests
  tags:
    - slivings
  

build_jobs:
  stage: build
  script:
    - npm i
    - npm run build 
  only:
    - merge_requests
  tags:
    - sliving


deploy_beta:
  stage: deploy
  script:
    - npm i
    - npm run build
  #Todo script to deploy
  only: 
    - merge_requests
    - develop
  tags:
    - sliving


release:
  stage: deploy
  script:
    - npm i 
    - npm run build
  #Todo script to release
  only:
    - merge_requests
    - master
  tags: 
    - sliving
  

