# This file is a template, and might need editing before it works on your project.
# variables:
#   GIT_SUBMODULE_STRATEGY: recursive

image: node:14

stages:
  - build-and-deploy

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

before_script:
  # Create ssh-key and pull submodule
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - echo -e "$SSH_DEPLOY_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - git submodule update --init --recursive

build-and-deploy:
  stage: build-and-deploy
  before_script:
    - export AWS_S3_BUCKET=$AWS_S3_BUCKET_BETA
  script:
    - npm install
    - npm install -g gatsby-cli
    # - ./node_modules/.bin/gatsby build --prefix-paths
    # - cp -rf src/images public/images
    # - ls public/
    # Chưa xử lý phần xóa các file cũ của folder /var/www/html/docs.sliving/. Hiện tại chỉ ghi đè các file cùng tên
    # - scp -i ~/.ssh/id_rsa -P 22006 -r public/* sst-ci@sst-ci.vm.sunshinetech.ai:/var/www/html/docs.sliving/
    - npm run build
    - npm run deploy
  only:
    - develop-v2
  tags:
    - hcm-share-docker-runner-1
