image: doctrine/nodejs-aws-cli:2022-01-13-aws-eb-cli-node14.18
stages:
  - test

before_script:
  - npm install

lint:
  stage: test
  script:
    - npm run lint
    - npm run build
  only:
    - merge_requests
    - develop
  tags:
    - hcm-share-docker-runner
